### ISSUE TITLE
 wrong "interpretation" of some media file

### ISSUE THREAD

**Issue by christian0903** [Maboroshy/Note-Station-to-markdown#22] opened 2021-01-23 12:42 UTC
Wonderful script, you saved my life.
Just found some media filename were not correctly "translated". It was the case with special char in the filename with % char
ex: filename in the media folder: 5-petit-de%CC%81jeuner.png
and the link was media 5-petit-de%25CC%2581jeuner.png
as you can see the script systematically skips the 2 digits following the % char
not a big deal, but opportunity for improvement

**Comment by Maboroshy** [comment] 2021-01-23 14:22
Thanks. I'll look into this.

**Comment by Maboroshy** [comment] 2021-02-14 06:53
The issue is fixed by @kevindurston21 with #25.

**Closed by Maboroshy** 2021-02-14 06:53 UTC
